version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    profiles: ['dev', 'dockerize']
    environment:
      POSTGRES_DB: librarygenius
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
      # HOST:CONTAINER_PORT

  backend:
    image: backend:1.0
    container_name: backend
    restart: always
    profiles: ['dockerize']
    depends_on:
      - postgres
    ports:
      - 3333:3333
